version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/cell_type_deconvolution.wdl
    testParameterFiles:
      - /tests/fixtures/dtangle.inputs.json
    name: cell-type-deconvolution
